// This file has been autogenerated from parsing an Objective-C header file added in Xcode.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;
using ZXing.Common;
using ZXing.QrCode;
using ZXing.Rendering;

namespace PaperTool
{
	public partial class DecryptionDetailsViewController : UIViewController
	{
		public DecryptionDetailsViewController (IntPtr handle) : base (handle)
		{
		}

		public override void ViewDidLoad ()
		{
			base.ViewDidLoad ();
			lblDetails.Text = Application.decryptionDetails;

			QRCodeWriter qrwriter = new QRCodeWriter();
			BitMatrix matrix = qrwriter.encode (Application.QRDetails, ZXing.BarcodeFormat.QR_CODE, 256, 256);
			BitmapRenderer renderer = new BitmapRenderer();
			using (UIImage img = renderer.Render (matrix, ZXing.BarcodeFormat.QR_CODE, Application.QRDetails)) {
				imgQRCode.Image = img;
			}

		}
	}
}
