// This file has been autogenerated from parsing an Objective-C header file added in Xcode.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;

namespace PaperTool
{
	public partial class PaperToolTabBarController : UITabBarController
	{
		public PaperToolTabBarController (IntPtr handle) : base (handle)
		{
		}
	}
}
